spring:
  application:
    name: es
  datasource:
    url: jdbc:mysql://localhost:3306/energy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml

kakao:
  auth:
    client:
    redirect: